description: |
  - Tag validation (only image-version tags like X.Y.Z allowed)
  - Docker image build and tagging
  - Image push to target registry
  - Security scan using Trivy
  - Report generation and artifact upload
  - Notification for delivery completion

inputs:
  scope:
    required: true
    description: "Gradle Task tier 1."
  module:
    required: true
    description: "Gradle Task tier 2 (belong to 'scope')."
  version:
    required: true
    description: "Docker Image version"
  docker_user:
    required: true
    description: "Username or service account used to authenticate to the Docker registry."
  docker_token:
    required: true
    description: "Access token or password used for Docker registry authentication."
  docker_repo:
    required: true
    description: "Target Docker registry repository or namespace to push the built image."
  slack:
    required: true
    description: "Incoming Slack Webhook URL used to send delivery status notifications."
  telegram_token:
    required: false
    description: "Telegram bot token used for sending notifications."
  telegram:
    required: false
    description: "Telegram chat/group ID to send messages to."
  discord:
    required: false
    description: "Discord webhook URL to send notifications."
  pat:
    required: false
    description: "GitHub Personal Access Token used for repository_dispatch events."

runs:
  using: composite
  steps:
    # ==========================================================
    # 🏗️ STEP 1: Build Docker image
    # Builds the Docker image using its module directory.
    # ==========================================================
    - name: 🏗️ Build Docker Image
      shell: bash
      run: |
        IMAGE_NAME="${{ inputs.docker_repo }}/${{ inputs.scope }}/${{ inputs.module }}:${{ inputs.version }}"
        SCOPE="${{ inputs.scope }}"
        MODULE="${{ inputs.module }}"
        echo "🏗️ Building Docker image: $IMAGE_NAME"
        echo "📦 Scope: $SCOPE | Module: $MODULE"
        docker build \
          -t "$IMAGE_NAME" \
          -f ".docker/Dockerfile" \
          --build-arg SCOPE="$SCOPE" \
          --build-arg MODULE="$MODULE" \
          .
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

    # ==========================================================
    # 🚀 STEP 2: Push Docker image
    # Authenticates and pushes the image to the target registry.
    # ==========================================================
    - name: 🚀 Push Docker Image
      shell: bash
      run: |
        echo "${{ inputs.docker_token }}" | docker login -u "${{ inputs.docker_user }}" --password-stdin
        docker push "$IMAGE_NAME"

    # ==========================================================
    # 🛡️ STEP 3: Scan Docker image vulnerabilities
    # ==========================================================
    - name: 🛡️ Scan Docker Image (Trivy)
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: ${{ env.IMAGE_NAME }}
        severity: HIGH,CRITICAL
        ignore-unfixed: true
        exit-code: 1

    # ==========================================================
    # 🧾 STEP 4: Generate build report
    # ==========================================================
    - name: 🧾 Generate Delivery Report
      if: ${{ always() }}
      shell: bash
      run: |
        DIGEST=$(docker images --digests --format "{{.Digest}}" | head -n1 || echo "N/A")
        echo "DIGEST=$DIGEST" >> $GITHUB_ENV
        echo "🧾 Delivery Report" > report.txt
        echo "Status: ${{ job.status }}" >> report.txt
        echo "Image: $IMAGE_NAME" >> report.txt
        echo "Digest: $DIGEST" >> report.txt
        echo "Ref: $GITHUB_REF_NAME" >> report.txt

    # ==========================================================
    # 📦 STEP 5: Upload delivery artifacts
    # ==========================================================
    - name: 📤 Upload Delivery Report
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: release-report-${{ inputs.scope }}-${{ inputs.module }}-${{ inputs.version }}
        path: report.txt

    # ==========================================================
    # 📣 STEP 6: Notifications
    # ==========================================================
    - name: 📣 Notify (Delivery Complete)
      if: ${{ always() }}
      shell: bash
      run: |
        STATUS="${{ job.status }}"
        SCOPE="${{ inputs.scope }}"
        MODULE="${{ inputs.module }}"
        VERSION="${{ inputs.version }}"
        if [ "$STATUS" = "success" ]; then
          MESSAGE="✅ *Delivery completed successfully* for tag: $GITHUB_REF_NAME"
          MESSAGE="$MESSAGE\n📦 Image: ${SCOPE}/${MODULE}:${VERSION}"
          MESSAGE="$MESSAGE\n🔑 Digest: ${DIGEST:-N/A}"
        else
          MESSAGE="❌ *Delivery failed* for tag: $GITHUB_REF_NAME"
          MESSAGE="$MESSAGE\n🧩 Scope: ${SCOPE} | Module: ${MODULE}"
        fi
        echo "🔔 Sending notifications..."
        curl -X POST -H "Content-Type: application/json" \
          --data "{\"text\":\"$MESSAGE\"}" ${{ inputs.slack }} || true
        curl -s -X POST "https://api.telegram.org/bot${{ inputs.telegram_token }}/sendMessage" \
          -d "chat_id=${{ inputs.telegram }}" \
          -d "text=$MESSAGE" || true
        curl -X POST \
          -H "Content-Type: application/json" \
          -d "{\"content\":\"$MESSAGE\"}" ${{ inputs.discord }} || true
        if [ "$STATUS" = "success" ]; then
          echo "🚀 Triggering downstream repository..."
          curl -X POST \
            -H "Authorization: Bearer ${{ inputs.pat }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/wliamp/java-deployment/dispatches \
            -d "{\"event_type\":\"delivery_completed\",\"client_payload\":{\"scope\":\"${SCOPE}\",\"module\":\"${MODULE}\",\"version\":\"${VERSION}\"}}"
        else
          echo "⚠️ Job failed, skipping downstream trigger."
        fi
