description: |
  - Tag validation (only image-version tags like X.Y.Z allowed)
  - Docker image build and tagging
  - Image push to target registry
  - Security scan using Trivy
  - Report generation and artifact upload
  - Notification for delivery completion

inputs:
  scope:
    required: true
    description: "Gradle Task tier 1."
  module:
    required: true
    description: "Gradle Task tier 2 (belong to 'scope')."
  version:
    required: true
    description: "Docker Image version"
  docker_user:
    required: true
    description: "Username or service account used to authenticate to the Docker registry."
  docker_token:
    required: true
    description: "Access token or password used for Docker registry authentication."
  docker_repo:
    required: true
    description: "Target Docker registry repository or namespace to push the built image."
  slack:
    required: true
    description: "Incoming Slack Webhook URL used to send delivery status notifications."
  telegram_token:
    required: false
    description: "Telegram bot token used for sending notifications."
  telegram:
    required: false
    description: "Telegram chat/group ID to send messages to."
  discord:
    required: false
    description: "Discord webhook URL to send notifications."
  pat:
    required: false
    description: "GitHub Personal Access Token used for repository_dispatch events."

runs:
  using: composite
  steps:
    # ==========================================================
    # ðŸ—ï¸ STEP 1: Build Docker image
    # Builds the Docker image using its module directory.
    # ==========================================================
    - name: ðŸ—ï¸ Build Docker Image
      shell: bash
      run: |
        IMAGE_NAME="${{ inputs.docker_repo }}/${{ inputs.scope }}/${{ inputs.module }}:${{ inputs.version }}"
        SCOPE="${{ inputs.scope }}"
        MODULE="${{ inputs.module }}"
        echo "ðŸ—ï¸ Building Docker image: $IMAGE_NAME"
        echo "ðŸ“¦ Scope: $SCOPE | Module: $MODULE"
        docker build \
          -t "$IMAGE_NAME" \
          -f ".docker/Dockerfile" \
          --build-arg SCOPE="$SCOPE" \
          --build-arg MODULE="$MODULE" \
          .
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

    # ==========================================================
    # ðŸš€ STEP 2: Push Docker image
    # Authenticates and pushes the image to the target registry.
    # ==========================================================
    - name: ðŸš€ Push Docker Image
      shell: bash
      run: |
        echo "${{ inputs.docker_token }}" | docker login -u "${{ inputs.docker_user }}" --password-stdin
        docker push "$IMAGE_NAME"

    # ==========================================================
    # ðŸ›¡ï¸ STEP 3: Scan Docker image vulnerabilities
    # ==========================================================
    - name: ðŸ›¡ï¸ Scan Docker Image (Trivy)
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: ${{ env.IMAGE_NAME }}
        severity: HIGH,CRITICAL
        ignore-unfixed: true
        exit-code: 1

    # ==========================================================
    # ðŸ§¾ STEP 4: Generate build report
    # ==========================================================
    - name: ðŸ§¾ Generate Delivery Report
      shell: bash
      run: |
        DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' "$IMAGE_NAME")
        echo "DIGEST=$DIGEST" >> $GITHUB_ENV
        echo "âœ… Build completed for $IMAGE_NAME" > report.txt
        echo "ðŸ”‘ Digest: $DIGEST" >> report.txt

    # ==========================================================
    # ðŸ“¦ STEP 5: Upload delivery artifacts
    # ==========================================================
    - name: ðŸ“¤ Upload Delivery Report
      uses: actions/upload-artifact@v4
      with:
        name: release-report-${{ inputs.scope }}-${{ inputs.module }}-${{ inputs.version }}
        path: report.txt

    # ==========================================================
    # ðŸ“£ STEP 6: Notifications
    # ==========================================================
    - name: ðŸ“£ Notify (Delivery Complete)
      shell: bash
      run: |
        MESSAGE="âœ… CD Delivery completed successfully for tag: $GITHUB_REF_NAME"
        MESSAGE="$MESSAGE\nðŸ“¦ Image: ${{ inputs.scope }}/${{ inputs.module }}:${{ inputs.version }}"
        curl -X POST -H "Content-Type: application/json" \
          --data "{\"text\":\"$MESSAGE\"}" ${{ inputs.slack }}
        curl -s -X POST "https://api.telegram.org/bot${{ inputs.telegram_token }}/sendMessage" \
          -d "chat_id=${{ inputs.telegram }}" \
          -d "text=$MESSAGE"
        curl -X POST \
          -H "Content-Type: application/json" \
          -d "{\"content\":\"$MESSAGE\"}" ${{ inputs.discord }}
        curl -X POST \
          -H "Authorization: Bearer ${{ inputs.pat }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/wliamp/java-deployment/dispatches \
          -d "{\"event_type\":\"delivery_completed\",\"client_payload\":{\"scope\":\"${{ inputs.scope }}\",\"module\":\"${{ inputs.module }}\",\"version\":\"${{ inputs.version }}\"}}"
