description: |
  - Detects and commits any updates to README and docker-compose files, then opens a Pull Request.
  - Mirrors the latest deployment artifacts into a dedicated deployment repository.

inputs:
  pat:
    required: true
    description: "GitHub Personal Access Token (PAT) used for authentication with GitHub CLI when creating Pull Requests."
  key:
    required: true
    description: "SSH Deploy Key granting write access to the external deployment repository."

runs:
  using: composite
  steps:
    # =============================================================
    # Step 1: Detect and push README/Compose changes
    #
    # - Creates a new temporary branch for settings or Compose updates.
    # - Configures a bot identity for automated commits.
    # - Commits README.md and docker-compose.yml only if changes are detected.
    # - Pushes the branch and opens a Pull Request targeting 'main'.
    # - Avoids duplication if a similar PR already exists.
    # =============================================================
    - name: 💾 Commit README & Compose
      id: compose
      shell: bash
      continue-on-error: true
      env:
        GH_TOKEN: ${{ inputs.pat }}
      run: |
        set -euo pipefail
        echo "🔍 Checking for README or docker-compose changes..."
        branch="auto/settings-$(date +%s)"
        git config user.name "settings[bot]"
        git config user.email "settings[bot]@users.noreply.github.com"
        git checkout -b "$branch"
        git add README.md docker-compose.yml
        if git diff --cached --quiet; then
          echo "✅ No README or compose changes detected."
          exit 0
        fi
        git commit -m "chore(root): sync Gradle structure"
        git push origin "$branch"
        gh pr create \
          --title "chore(root): sync Gradle structure" \
          --body "Auto-sync based on settings.gradle." \
          --base main \
          --head "$branch" || echo "ℹ️ Pull request already exists."

    # =============================================================
    # Step 2: Sync deployment artifacts to external Deploy repo
    #
    # - Authenticates via SSH Deploy Key to access 'java-deployment' repository.
    # - Clones the repo into a temporary workspace.
    # - Iterates through all folders under ./deploy in the source repository.
    # - Replaces corresponding folders in the Deploy repo with updated artifacts.
    # - Commits only if actual changes exist, avoiding redundant commits.
    # - Pushes updates directly to the 'main' branch of the Deploy repository.
    # =============================================================
    - name: 📦 Commit & Push to Deploy repo
      id: deploy
      shell: bash
      continue-on-error: true
      run: |
        set -euo pipefail
        echo "🚀 Syncing deployment artifacts..."
        mkdir -p ~/.ssh
        echo "${{ inputs.key }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts 2>/dev/null
        DEPLOY_DIR="${{ runner.temp }}/java-deployment"
        git clone --depth=1 git@github.com:wliamp/java-deployment.git "$DEPLOY_DIR"
        cd "$DEPLOY_DIR"
        FOLDERS=()
        for d in "$GITHUB_WORKSPACE/deploy"/*/; do
          [ -d "$d" ] || continue
          FOLDERS+=("$(basename "$d")")
        done
        for folder in "${FOLDERS[@]}"; do
          SRC="${GITHUB_WORKSPACE}/deploy/$folder"
          echo "📦 Syncing $folder..."
          rm -rf "$folder"
          mkdir -p "$folder"
          cp -r "$SRC"/* "$folder"/ || echo "⚠️ No files in $SRC"
        done
        git config user.name "settings[bot]"
        git config user.email "settings[bot]@users.noreply.github.com"
        git add -A
        if git diff --cached --quiet; then
          echo "✅ No changes in deployment artifacts."
        else
          git commit -m "chore: sync deployment artifacts"
          git push origin main
        fi

    # =============================================================
    # Step 3: Reporting
    # =============================================================
    - name: 🧾 Generate Report
      if: ${{ always() }}
      shell: bash
      run: |
        STATUS_COMPOSE="${{ steps.compose.outcome }}"
        STATUS_DEPLOY="${{ steps.deploy.outcome }}"
        OVERALL="success"
        if [ "$STATUS_COMPOSE" != "success" ] || [ "$STATUS_DEPLOY" != "success" ]; then
          OVERALL="failure"
        fi
        echo "🧾 Generating synchronization report..."
        {
          echo "🔧 Sync Report"
          echo "==============="
          echo "🧩 Compose Step: $STATUS_COMPOSE"
          echo "📦 Deploy Step: $STATUS_DEPLOY"
          echo "-------------------------------"
          echo "✅ Overall Result: $OVERALL"
          echo "📅 Run ID: $GITHUB_RUN_ID"
          echo "🔗 Repository: $GITHUB_REPOSITORY"
          echo "👤 Triggered by: $GITHUB_ACTOR"
          echo "🕒 Timestamp: $(date -u)"
        } > sync-report.txt

    - name: 📤 Upload Sync Report Artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: sync-report
        path: sync-report.txt
