description: |
  - Auto-tagging from dev branch
  - Semantic versioning
  - Ensure Release
  - Docker reproducible build
  - Security scan
  - Manual approval
  - Reporting
inputs:
  scope:
    description: "Java Spring Boot independent application"
    required: true
  service:
    description: "A Service belong to Scope"
    required: true
  version:
    description: "Target semantic version"
    required: true
  key:
    required: true
    description: "SSH Deploy Key granting write access in this repository."
  pat:
    required: true
    description: "GitHub Personal Access Token (PAT) used for authentication with GitHub CLI when creating Pull Requests."
runs:
  using: composite
  steps:
    - run: |
        set -e
        RELEASE_BRANCH="release/${{ inputs.scope }}/${{ inputs.service }}"
        echo "🔍 Checking branch: $RELEASE_BRANCH"
        git fetch origin dev --quiet
        git fetch origin "$RELEASE_BRANCH" --quiet || true
        if git rev-parse --verify "origin/$RELEASE_BRANCH" >/dev/null 2>&1; then
          echo "✅ Found existing branch: $RELEASE_BRANCH"
          git checkout -B "$RELEASE_BRANCH" "origin/$RELEASE_BRANCH"
          echo "🔄 Merging latest dev changes into $RELEASE_BRANCH..."
          git merge --no-edit origin/dev || true
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "📦 Push updated $RELEASE_BRANCH after sync"
            mkdir -p ~/.ssh
            echo "${{ inputs.key }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts 2>/dev/null
            git config user.name "release[bot]"
            git config user.email "release[bot]@users.noreply.github.com"
            git push origin "$RELEASE_BRANCH"
          else
            echo "✅ Release branch already up to date with dev."
          fi
        else
          echo "🆕 Creating new branch: $RELEASE_BRANCH from origin/dev"
          git checkout -b "$RELEASE_BRANCH" origin/dev
          git push origin "$RELEASE_BRANCH"
        fi
        echo "branch=$RELEASE_BRANCH" >> $GITHUB_OUTPUT
      id: branch
      shell: bash
    - run: |
        TAG="${{ inputs.version }}"
        BRANCH="${{ steps.branch.outputs.branch }}"
        mkdir -p .release-log
        LOG=".release-log/tag-create.log"
        echo "🔍 Checking if tag '$TAG' exists..." | tee -a "$LOG"
        git fetch origin --tags --quiet
        if git rev-parse "$TAG" >/dev/null 2>&1; then
          echo "❌ Tag already exists: $TAG" | tee -a "$LOG"
          echo "exists=true" >> $GITHUB_OUTPUT
          exit 0
        fi
        echo "🔑 Configuring SSH Deploy Key..."
        mkdir -p ~/.ssh
        echo "${{ inputs.key }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts 2>/dev/null
        git config user.name "release[bot]"
        git config user.email "release[bot]@users.noreply.github.com"
        git checkout "$BRANCH"
        git tag -a "$TAG" -m "Automated release $TAG for ${{ inputs.scope }}/${{ inputs.service }}"
        git push git@github.com:${{ github.repository }} "$TAG"
        echo "✅ Created and pushed tag: $TAG on $BRANCH" | tee -a "$LOG"
        echo "exists=false" >> $GITHUB_OUTPUT
      id: tag
      shell: bash
    - run: |
        IMAGE="ghcr.io/${{ github.repository_owner }}/${{ inputs.scope }}-${{ inputs.service }}:${{ inputs.version }}"
        docker build \
          --cache-from="$IMAGE" \
          -t "$IMAGE" \
          -f .docker/Dockerfile \
          --build-arg SCOPE="${{ inputs.scope }}" \
          --build-arg SERVICE="${{ inputs.service }}" .
        echo "IMAGE=$IMAGE" >> $GITHUB_ENV
      if: success()
      shell: bash
    - run: |
        HASH1=$(docker inspect --format='{{.Id}}' "$IMAGE")
        docker build \
          -t "$IMAGE-test" \
          -f .docker/Dockerfile \
          --build-arg SCOPE="${{ inputs.scope }}" \
          --build-arg SERVICE="${{ inputs.service }}" .
        HASH2=$(docker inspect --format='{{.Id}}' "$IMAGE-test")
        if [[ "$HASH1" != "$HASH2" ]]; then
          echo "❌ Non-deterministic build detected!"
          exit 1
        fi
        echo "✅ Reproducible build confirmed"
      if: success()
      shell: bash
    - uses: github/codeql-action/init@v3
      with:
        languages: java
      if: success()
    - uses: github/codeql-action/analyze@v3
      if: success()
    - uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: ${{ env.IMAGE }}
        severity: HIGH,CRITICAL
        ignore-unfixed: true
        exit-code: 1
      if: success()
    - uses: actions/upload-artifact@v4
      with:
        name: release-report-${{ inputs.scope }}-${{ inputs.service }}-${{ inputs.version }}
        path: .release-log/
      if: always()
    - run: |
        RELEASE_BRANCH="${{ steps.branch.outputs.branch }}"
        TITLE="🚀 Merge ${RELEASE_BRANCH} → main"
        BODY=$(cat <<EOF
        ### 🔄 Automated Release PR
        This pull request was automatically created after successful:
          - ✅ Sync from \`dev\`
          - ✅ Tag \`${{ inputs.version }}\`
          - ✅ Build & Reproducibility Check
          - ✅ CodeQL (SAST)
          - ✅ Trivy (Container Security Scan)

          #### 📦 Service Details
          - **Scope:** \`${{ inputs.scope }}\`
          - **Service:** \`${{ inputs.service }}\`
          - **Version:** \`${{ inputs.version }}\`
        > Created by the \`release[bot]\` automation workflow for controlled promotion to \`main\`.
        EOF
        )
        gh pr create \
          --title "$TITLE" \
          --body "$BODY"
          --base main \
          --head "$RELEASE_BRANCH" || echo "ℹ️ Pull Request already exists."
      env:
        GH_TOKEN: ${{ inputs.pat }}
      if: success()
      shell: bash
