description: |
  - Dependency caching
  - Static & Security analysis
  - Testing & Building
  - Artifact upload
  - Aggregate validation
  - Image pre-build & vulnerability scan
inputs:
  scope:
    description: "Java Spring Boot independent application"
    required: true
  service:
    description: "A Service belong to Scope"
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'
    - uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle-
    - run: ./gradlew :${{ inputs.scope }}:${{ inputs.service }}:check
      shell: bash
    - run: ./gradlew dependencies --configuration runtimeClasspath > deps.txt
      working-directory: ./${{ inputs.scope }}/${{ inputs.service }}
      shell: bash
    - uses: anchore/scan-action@v4
      with:
        path: ./${{ inputs.scope }}/${{ inputs.service }}/deps.txt
        fail-build: true
        severity-cutoff: high
    - run: ./gradlew :${{ inputs.scope }}:${{ inputs.service }}:clean build jacocoTestReport
      env:
        SPRING_PROFILES_ACTIVE: test
      shell: bash
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.scope }}-${{ inputs.service }}-test-report
        path: ${{ inputs.scope }}/${{ inputs.service }}/build/reports/tests/test
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.scope }}-${{ inputs.service }}-coverage-report
        path: ${{ inputs.scope }}/${{ inputs.service }}/build/reports/jacoco/test/html
    - run: |
        docker build \
          --target build \
          -t ci-${{ inputs.scope }}-${{ inputs.service }}:prebuild \
          -f .docker/Dockerfile \
          --build-arg SCOPE="${{ inputs.scope }}" \
          --build-arg SERVICE="${{ inputs.service }}" .
      shell: bash
    - uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: ci-${{ inputs.scope }}-${{ inputs.service }}:prebuild
        severity: HIGH,CRITICAL
        ignore-unfixed: true
        exit-code: 1
