name: CD Deploy

on:
  workflow_dispatch:
    inputs:
      repo:
        description: "Docker Image repo name"
        required: true
      ver:
        description: "Docker image version"
        required: true

jobs:
  delpoy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/cd-deploy
      with:
        image_repo: ${{ github.event.inputs.repo }}
        image_ver: ${{ github.event.inputs.ver }}
        manifests: ${{ vars.K8S_MANIFESTS_BASE }}/${{ github.event.inputs.repo }}

        image_space: ${{ vars.DOCKERHUB_REPO }}
        approvers: ${{ vars.APPROVERS }}
        staging_cluster: ${{ vars.K8S_STAGING_CLUSTER }}
        prod_cluster: ${{ vars.K8S_PROD_CLUSTER }}
        staging_namespace: ${{ vars.K8S_STAGING_NAMESPACE }}
        prod_namespace: ${{ vars.K8S_PROD_NAMESPACE }}
        prom: ${{ vars.PROM_PUSH_URL }}
        grafana: ${{ vars.GRAFANA_URL }}

        slack: ${{ secrets.SLACK_WEBHOOK_URL }}
        k8s_config: ${{ secrets.K8S_CONFIG_BASE64 }}
        grafana_key: ${{ secrets.GRAFANA_API_KEY }}

