name: CD Pipeline

on:
  push:
    branches: ["main"]
  release:
    types: [published]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cmc: ${{ steps.filter.outputs.cmc }}
      odr-cko: ${{ steps.filter.outputs.odr-cko }}
      odr-pay: ${{ steps.filter.outputs.odr-pay }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: wliamp/configurations
          path: config
          token: ${{ secrets.CONFIG_REPO_TOKEN }}

      - name: Filter changed paths
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            cmc:
              - 'communication/**'
            odr-cko:
              - 'order-lifecycle/checkout/**'
            odr-pay:
              - 'order-lifecycle/payment/**'

  # ------------------------
  # Build & Push CMC
  # ------------------------
  build-cmc:
    needs: setup
    if: needs.setup.outputs.cmc == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push cmc image
        run: |
          IMAGE=wliamp/communication-service
          TAG=${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
          docker build -t $IMAGE:$TAG ./communication
          docker push $IMAGE:$TAG

  # ------------------------
  # Build & Push ODR/CKO
  # ------------------------
  build-odr-cko:
    needs: setup
    if: needs.setup.outputs.odr-cko == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push odr-cko image
        run: |
          IMAGE=wliamp/checkout-service
          TAG=${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
          docker build -t $IMAGE:$TAG ./order-lifecycle/checkout
          docker push $IMAGE:$TAG

  # ------------------------
  # Build & Push ODR/PAY
  # ------------------------
  build-odr-pay:
    needs: setup
    if: needs.setup.outputs.odr-pay == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push odr-pay image
        run: |
          IMAGE=wliamp/payment-service
          TAG=${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
          docker build -t $IMAGE:$TAG ./order-lifecycle/payment
          docker push $IMAGE:$TAG
