name: CD Pipeline

on:
  push:
    branches:
      - 'releases/**'
  pull_request:
    branches:
      - 'releases/**'

jobs:
  # ------------------------
  # detect changed services & prepare matrix
  # ------------------------
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            cmc:
              - 'communication/**'
            odr-cko:
              - 'order-lifecycle/checkout/**'
            odr-pay:
              - 'order-lifecycle/payment/**'

      - id: set-matrix
        run: |
          services=()

          if [[ "${{ steps.filter.outputs.cmc }}" == "true" ]]; then
            services+=('{"service":"cmc","context":"./communication","image":"wliamp/communication-service"}')
          fi
          if [[ "${{ steps.filter.outputs.odr-cko }}" == "true" ]]; then
            services+=('{"service":"odr-cko","context":"./order-lifecycle/checkout","image":"wliamp/checkout-service"}')
          fi
          if [[ "${{ steps.filter.outputs.odr-pay }}" == "true" ]]; then
            services+=('{"service":"odr-pay","context":"./order-lifecycle/payment","image":"wliamp/payment-service"}')
          fi

          echo "matrix=$(jq -c -n --argjson s "[${services[*]}]" '{include: $s}')" >> $GITHUB_OUTPUT

  # ------------------------
  # build & push Docker images
  # ------------------------
  build:
    needs: setup
    if: needs.setup.outputs.matrix != '{"include":[]}'
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/setup-buildx-action@v2

      - name: Extract version from branch name
        id: extract_version
        run: echo "version=${GITHUB_REF_NAME#releases/}" >> $GITHUB_OUTPUT

      - name: Build & Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          push: true
          tags: |
            ${{ matrix.image }}:latest
            ${{ matrix.image }}:${{ github.sha }}
            ${{ matrix.image }}:${{ steps.extract_version.outputs.version }}
