name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test-cmc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - run: |
          ./gradlew :cmc:clean test

  build-auth:
    runs-on: ubuntu-latest
    needs: test-cmc
    if: success()
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          docker build -t cmc:latest .
          docker push cmc:latest

  test-odr-cko:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - run: |
          ./gradlew :odr:cko:clean test

  build-odr-cko:
    runs-on: ubuntu-latest
    needs: test-odr-cko
    if: success()
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          docker build -t odr:cko:latest .
          docker push odr:cko:latest

  test-odr-pay:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - run: |
          ./gradlew :odr:pay:clean test

  build-odr-pay:
    runs-on: ubuntu-latest
    needs: test-odr-pay
    if: success()
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          docker build -t odr:pay:latest .
          docker push odr:pay:latest
