name: CI Pipeline

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cmc: ${{ steps.filter.outputs.cmc }}
      odr-cko: ${{ steps.filter.outputs.odr-cko }}
      odr-pay: ${{ steps.filter.outputs.odr-pay }}
    steps:
      - uses: actions/checkout@v4

      - name: Filter changed paths
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            cmc:
              - 'communication/**'
            odr-cko:
              - 'order-lifecycle/checkout/**'
            odr-pay:
              - 'order-lifecycle/payment/**'

  test-cmc:
    needs: setup
    if: needs.setup.outputs.cmc == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run static checks (Checkstyle/Spotbugs)
        run: ./gradlew :cmc:check

      - name: Run tests + build + coverage
        env:
          SPRING_PROFILES_ACTIVE: test
        run: ./gradlew :cmc:clean build jacocoTestReport

      - uses: actions/upload-artifact@v4
        with:
          name: cmc-test-report
          path: cmc/build/reports/tests/test

      - uses: actions/upload-artifact@v4
        with:
          name: cmc-coverage-report
          path: cmc/build/reports/jacoco/test/html

  test-odr-cko:
    needs: setup
    if: needs.setup.outputs.odr-cko == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run static checks
        run: ./gradlew :odr:cko:check

      - name: Run tests + build + coverage
        env:
          SPRING_PROFILES_ACTIVE: test
        run: ./gradlew :odr:cko:clean build jacocoTestReport

      - uses: actions/upload-artifact@v4
        with:
          name: odr-cko-test-report
          path: order-lifecycle/checkout/build/reports/tests/test

      - uses: actions/upload-artifact@v4
        with:
          name: odr-cko-coverage-report
          path: order-lifecycle/checkout/build/reports/jacoco/test/html

  test-odr-pay:
    needs: setup
    if: needs.setup.outputs.odr-pay == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run static checks
        run: ./gradlew :odr:pay:check

      - name: Run tests + build + coverage
        env:
          SPRING_PROFILES_ACTIVE: test
        run: ./gradlew :odr:pay:clean build jacocoTestReport

      - uses: actions/upload-artifact@v4
        with:
          name: odr-pay-test-report
          path: order-lifecycle/payment/build/reports/tests/test

      - uses: actions/upload-artifact@v4
        with:
          name: odr-pay-coverage-report
          path: order-lifecycle/payment/build/reports/jacoco/test/html
