name: CI Pipeline

on:
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["dev", "main"]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cmc: ${{ steps.filter.outputs.cmc }}
      odr-cko: ${{ steps.filter.outputs.odr-cko }}
      odr-pay: ${{ steps.filter.outputs.odr-pay }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: wliamp/configurations
          path: config
          token: ${{ secrets.CONFIG_REPO_TOKEN }}

      - name: Filter changed paths
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            cmc:
              - 'communication/**'
            odr-cko:
              - 'order-lifecycle/checkout/**'
            odr-pay:
              - 'order-lifecycle/payment/**'

  test-cmc:
    needs: setup
    if: needs.setup.outputs.cmc == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run unit tests for cmc
        env:
          SPRING_PROFILES_ACTIVE: test
        run: ./gradlew :cmc:clean test

  test-odr-cko:
    needs: setup
    if: needs.setup.outputs.odr-cko == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run unit tests for odr-cko
        env:
          SPRING_PROFILES_ACTIVE: test
        run: ./gradlew :odr:cko:clean test

  test-odr-pay:
    needs: setup
    if: needs.setup.outputs.odr-pay == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run unit tests for odr-pay
        env:
          SPRING_PROFILES_ACTIVE: test
        run: ./gradlew :odr:pay:clean test
