name: Deliver

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deliver:
    if: >
      !contains(vars.EXCLUDE_DELIVER_ACTORS, github.actor)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - id: parse
        run: bash .shell/deliver

      - uses: ./.github/actions/deliver
        with:
          scope: ${{ steps.parse.outputs.scope }}
          module: ${{ steps.parse.outputs.module }}
          version: ${{ steps.parse.outputs.version }}

          docker_user: ${{ vars.DOCKERHUB_USER }}
          docker_repo: ${{ vars.DOCKERHUB_REPO }}

          docker_token: ${{ secrets.DOCKERHUB_TOKEN }}
          slack: ${{ secrets.SLACK_WEBHOOK_URL }}
          telegram_token: ${{ secrets.TELEGRAM_TOKEN }}
          telegram: ${{ secrets.TELEGRAM_CHAT_ID }}
          discord: ${{ secrets.DISCORD_WEBHOOK_URL }}
          pat: ${{ secrets.JAVA_DEPLOYMENT_PAT }}
