name: Deliver

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deliver:
    if: >
      !contains(vars.EXCLUDE_DELIVER_ACTORS, github.actor)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/deliver
        with:
          docker_user: ${{ vars.DOCKERHUB_USER }}
          docker_repo: ${{ vars.DOCKERHUB_REPO }}

          docker_token: ${{ secrets.DOCKERHUB_TOKEN }}
          slack: ${{ secrets.SLACK_WEBHOOK_URL }}
