name: Deploy

on:
  workflow_dispatch:
    inputs:
      repo:
        description: "Repository name of the Docker image (service name)."
        required: true
      ver:
        description: "Docker image version tag to deploy (e.g., '1.0.0' or commit SHA)."
        required: true

jobs:
  delpoy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/deploy
      with:
        image_repo: ${{ github.event.inputs.repo }}
        image_ver: ${{ github.event.inputs.ver }}
        charts: deploy/charts/${{ github.event.inputs.repo }}

        image_space: ${{ vars.DOCKERHUB_REPO }}
        approvers: ${{ vars.INCLUDE_DEPLOY_ACTORS }}
        staging_cluster: ${{ vars.K8S_STAGING_CLUSTER }}
        prod_cluster: ${{ vars.K8S_PROD_CLUSTER }}
        staging_namespace: ${{ vars.K8S_STAGING_NAMESPACE }}
        prod_namespace: ${{ vars.K8S_PROD_NAMESPACE }}
        prom: ${{ vars.PROM_PUSH_URL }}
        grafana: ${{ vars.GRAFANA_URL }}

        slack: ${{ secrets.SLACK_WEBHOOK_URL }}
        k8s_config: ${{ secrets.K8S_CONFIG_BASE64 }}
        grafana_token: ${{ secrets.GRAFANA_ACCOUNT_TOKEN }}
