name: Prepare Release
on:
  schedule:
    - cron: "0 0 * * 1"
jobs:
  resolve-version:
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev
          sparse-checkout: settings.gradle
      - run: bash .shell/pre-release
        env:
          DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_REPO: ${{ vars.DOCKERHUB_REPO }}
        id: resolve
    outputs:
      matrix: ${{ steps.resolve.outputs.matrix }}
    runs-on: ubuntu-latest
  pre-release:
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev
      - uses: wliamp/action/.github/actions/pre-release@main
        with:
          scope: ${{ matrix.scope }}
          service: ${{ matrix.service }}
          version: ${{ matrix.version }}
          key: ${{ secrets.JAVA_DK }}
          pat: ${ secrets.JAVA_PAT }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.resolve-version.outputs.matrix) }}
    needs: resolve-version
    runs-on: ubuntu-latest
