name: Settings

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ settings.gradle ]
  pull_request:
    branches: [ main ]
    paths: [ settings.gradle ]

jobs:
  sync-settings:
    if: contains(vars.INCLUDE_SETTINGS_ACTORS, github.actor)
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          sparse-checkout: settings.gradle

      - run: bash .shell/settings

      - uses: ./.github/actions/settings
        with:
          pat: ${{ secrets.PAT }}
          key: ${{ secrets.DEPLOY_KEY }}
