name: Settings

on:
  push:
    branches: [ main ]
    paths: [ settings.gradle ]

jobs:
  settings:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 2
          sparse-checkout: settings.gradle

      - run: bash .shell/settings

      - uses: ./.github/actions/settings
        with:
          pat: ${{ secrets.JAVA_PAT }}
          key: ${{ secrets.JAVA_DEPLOYMENT_DK }}
